SYSTEM:
  MAP: [
    "test_44.yaml",
    "test_68.yaml",
    "test_32.yaml",
    "test_77.yaml",
    "test_92.yaml",
    "test_24.yaml",
    "test_82.yaml",
    "map.yaml",
    "simple-map.yaml",
    "test_15.yaml",
    "test_95.yaml",
    "test_37.yaml",
    "test_70.yaml",
    "test_74.yaml",
    "test_48.yaml",
    "test_91.yaml",
    "test_14.yaml",
    "test_66.yaml",
    "test_67.yaml",
    "test_64.yaml",
    "test_72.yaml",
    "no-wall.yaml",
    "test_65.yaml",
    "test_46.yaml",
    "test_80.yaml",
    "test_71.yaml",
    "test_86.yaml",
    "test_10.yaml",
    "test_58.yaml",
    "test_40.yaml",
    "test_17.yaml",
    "test_50.yaml",
    "test_54.yaml",
    "test_69.yaml",
    "test_21.yaml",
    "test_13.yaml",
    "test_43.yaml",
    "test_4.yaml",
    "test_60.yaml",
    "hard-map.yaml",
    "test_76.yaml",
    "test_49.yaml",
    "test_30.yaml",
    "test_73.yaml",
    "test_19.yaml",
    "test_53.yaml",
    "test_56.yaml",
    "test_25.yaml",
    "test_63.yaml",
    "test_27.yaml",
    "test_9.yaml",
    "test_61.yaml",
    "test_47.yaml",
    "test_51.yaml",
    "test_41.yaml",
    "test_93.yaml",
    "test_8.yaml",
    "test_99.yaml",
    "test_75.yaml",
    "test_11.yaml",
    "test_85.yaml",
    "test_20.yaml",
    "test_36.yaml",
    "test_89.yaml",
    "test_97.yaml",
    "test_55.yaml",
    "test_52.yaml",
    "test_16.yaml",
    "test_2.yaml",
    "test_5.yaml",
    "test_28.yaml",
    "test_90.yaml",
    "test_94.yaml",
    "test_26.yaml",
    "test_39.yaml",
    "test_29.yaml",
    "test_3.yaml",
    "test_78.yaml",
    "test_12.yaml",
    "test_87.yaml",
    "test_62.yaml",
    "test_45.yaml",
    "test_100.yaml",
    "test_83.yaml",
    "test_57.yaml",
    "test_81.yaml",
    "test_7.yaml",
    "test_59.yaml",
    "test_18.yaml",
    "test_1.yaml",
    "test_88.yaml",
    "test_96.yaml",
    "test_38.yaml",
    "test_35.yaml",
    "test_31.yaml",
    "test_22.yaml",
    "test_84.yaml",
    "test_98.yaml",
    "test_23.yaml",
    "test_79.yaml",
    "test_6.yaml",
    "test_33.yaml",
    "test_34.yaml",
    "test_42.yaml",
  ]
  SAVE_DIR: "./output"
