SYSTEM:
  MAP: [
    "map.yaml",
    "simple-map.yaml",
    "no-wall.yaml",
    "test_10.yaml",
    "test_4.yaml",
    "hard-map.yaml",
    "test_9.yaml",
    "test_8.yaml",
    "test_2.yaml",
    "test_5.yaml",
    "test_3.yaml",
    "test_7.yaml",
    "test_1.yaml",
    "test_6.yaml",
  ]
  SAVE_DIR: "./output"
