SYSTEM:
  MAP: [
    "test_44.yaml",
    "test_32.yaml",
    "test_24.yaml",
    "map.yaml",
    "simple-map.yaml",
    "test_15.yaml",
    "test_37.yaml",
    "test_48.yaml",
    "test_14.yaml",
    "no-wall.yaml",
    "test_46.yaml",
    "test_10.yaml",
    "test_40.yaml",
    "test_17.yaml",
    "test_50.yaml",
    "test_21.yaml",
    "test_13.yaml",
    "test_43.yaml",
    "test_4.yaml",
    "hard-map.yaml",
    "test_49.yaml",
    "test_30.yaml",
    "test_19.yaml",
    "test_25.yaml",
    "test_27.yaml",
    "test_9.yaml",
    "test_47.yaml",
    "test_41.yaml",
    "test_8.yaml",
    "test_11.yaml",
    "test_20.yaml",
    "test_36.yaml",
    "test_0.yaml",
    "test_16.yaml",
    "test_2.yaml",
    "test_5.yaml",
    "test_28.yaml",
    "test_26.yaml",
    "test_39.yaml",
    "test_29.yaml",
    "test_3.yaml",
    "test_12.yaml",
    "test_45.yaml",
    "test_7.yaml",
    "test_18.yaml",
    "test_1.yaml",
    "test_38.yaml",
    "test_35.yaml",
    "test_31.yaml",
    "test_22.yaml",
    "test_23.yaml",
    "test_6.yaml",
    "test_33.yaml",
    "test_34.yaml",
    "test_42.yaml",
  ]
  SAVE_DIR: "./output"
