name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v2
      with:
        python-version: 3.7

    - name: Clean Useless File
      run: make clean
      
    - name: Algorithm Run
      run: make run MAP_NUM=1 BOUNDARY_X=50 BOUNDARY_Y=50 &> run.log
